### PR TITLE
Refactor, simplify and modernize GCS sample

### PR DESCRIPTION
**Pull request by Capstan**
* Pull up api client dependencies to associated 1.20.0 version and update Guava to latest, 18.0.
* Move use of API to v1
* Pull out specific uses into \*Example.java files.
* Exercise several such uses by the main StorageSample class.
* Demonstrate md5 and crc32c validation.
* Upload/download progress and ACL editing from the original sample have been removed.
* Update instructions to reference github instead of the old code.google.com.

https://codereview.appspot.com/236910043/
https://github.com/google/google-api-java-client/issues/938

### CODE REVIEW

**Comment by Capstan** [comment]
Everyone has LGTMed the [code review](https://codereview.appspot.com/236910043/), so this pull request is ready for inclusion.

**Comment by Capstan** [comment]
Committed in [af27369683](https://github.com/google/google-api-java-client-samples/commit/af27369683f2f1815b1c3e9dc91b2efcd2d3f125).

**Comment by Capstan** [comment]
@wonderfly I think that, despite you having already committed these changes in some kind of commit, this pull request isn't resolved, since I'm perennially showing these diffs between my master (which has no further changes) and google/master. I think merging this would be a no-op for code differences, but maybe fix the git accounting in some fashion I do not yet fully comprehend.

**Comment by ejona86** [comment]
The change was cherry-picked. That keeps the git history clean and removes all the review noise.

**Pull request closed without merging**
